### ISSUE TITLE
[BUG] opened application is opening in a "tree/family" of rust program.

### ISSUE THREAD

**Issue by McKpol** [longmathemagician/open_with#1]
Visual studio code shouldn't be there
![image](https://github.com/longmathemagician/open_with/assets/104125769/f53ed8d1-b2fe-43e6-ab98-f3c4f85ef3c6)

In code is opening a .Ink file of program.

https://github.com/McKpol/ArcRun - This project (using open_with).

**Comment by longmathemagician** [comment]
I was looking into this the other day. It appears to be related to Tauri. I do have a fix, will clean it up  and cut a new release in the next couple of days.

**Comment by McKpol** [comment]
Yey!
I can't wait. But you gonna add run_as_administrator, aren't you?

![image](https://github.com/longmathemagician/open_with/assets/104125769/e2a80ed9-2919-4ba8-a11f-33f963d84e1b)
(don't take it seriously)
